version: "3.7"
services:
  db: 
    image:  postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - ./.env
    ports:
      - "5432:5432"
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/app
    depends_on:
      - db
volumes:
  db-data: